default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: fotobook_development

test:
  <<: *default
  database: fotobook_test

production:
  <<: *default
  database: fotobook_production
  username: myapp
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

